T2w: 'https://www.dropbox.com/s/1nbdfxb8tcrbnmc/trained_model.3d_fullres.Task100_hcp1200hippT2w.nnUNetTrainerV2.model_best.tar'
T1w: 'https://www.dropbox.com/s/emv52j1v2mome33/trained_model.3d_fullres.Task101_hcp1200_T1w.nnUNetTrainerV2.model_best.tar'
hippb500: 'https://www.dropbox.com/s/y827qqkuj1ey1jb/trained_model.3d_fullres.Task110_hcp1200_b1000crop.nnUNetTrainerV2.model_best.tar'
