# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: True
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install non-python dependencies
      run: |
        sudo apt-get install -y graphviz-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install snakebids
#    - name: Lint with flake8
#      run: |
        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test hippunfold CLI and workflow dry-run
      run: |
        export HIPPUNFOLD_CACHE_DIR=`pwd`/test_data/fake_models
        ./hippunfold/run.py test_data/bids_singleT2w test_out participant -np --modality T2w
        ./hippunfold/run.py test_data/bids_singleT2w test_out participant -np --modality T2w --hemi R
        ./hippunfold/run.py test_data/bids_singleT2w test_out participant -np --modality T2w --hemi L
        ./hippunfold/run.py test_data/bids_multiT2w test_out participant -np --modality T2w
        ./hippunfold/run.py test_data/bids_T1w test_out participant -np --modality T1w
        ./hippunfold/run.py test_data/bids_hippb500 test_out participant -np --modality hippb500
        ./hippunfold/run.py test_data/bids_T1w_longitudinal test_out participant -np --modality T1w
        ./hippunfold/run.py test_data/bids_singleT2w_longitudinal test_out participant -np --modality T2w
        ./hippunfold/run.py test_data/bids_segT2w test_out participant -np --modality segT2w
        ./hippunfold/run.py - test_out participant -np --modality cropseg --path_cropseg test_data/data_cropseg/sub-{subject}_hemi-{hemi}_dseg.nii.gz
        ./hippunfold/run.py - test_out participant -np --modality cropseg --path_cropseg test_data/data_cropseg_1hemi/sub-{subject}_hemi-{hemi}_dseg.nii.gz --hemi L


